# store token here after login
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NSwibmFtZSI6IkpvaG4gRG9lIiwidXNlcm5hbWUiOiJKb2huRG9lIiwiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzUzMDQ0ODQsImV4cCI6MTc3NTM5MDg4NH0.HY-DL4c7dXLte6OizXCkIHeKM36wmdAfQNYW4yc9kt0

### CREATE USER
POST http://localhost:3000/api/v1/users
content-type: application/json

{
  "name": "John Doe",
  "username": "JohnDoe",
  "email": "john@example.com",
  "password": "to-be-hashed-pw1",
  "role": "user"
}


#### LOGIN
POST http://localhost:3000/api/v1/auth/login
content-type: application/json

{
  "username": "JohnDoe",
  "password": "to-be-hashed-pw1"
}


#### GET AUTHENTICATED USER INFO
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer {{token}}



#### CREATE A CAT
POST http://localhost:3000/api/v1/cats
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="name"

Mirri
--MyBoundary
Content-Disposition: form-data; name="weight"

6
--MyBoundary
Content-Disposition: form-data; name="owner"

45
--MyBoundary
Content-Disposition: form-data; name="birthdate"

2023-10-08
--MyBoundary
Content-Disposition: form-data; name="cat"; filename="dog.jpg"
Content-Type: image/jpeg

< ./dog.jpg
--MyBoundary--


#### UPDATE CAT
PUT http://localhost:3000/api/v1/cats/57
Authorization: Bearer {{token}}
content-type: application/json

{
  "weight": 7
}


#### DELETE CAT
DELETE http://localhost:3000/api/v1/cats/57
Authorization: Bearer {{token}}
